# confidential_terms.yaml
# Purpose: Define sensitive terms and protected categories for redaction
# Location: app/config/patterns/confidential_terms.yaml

identity_terms:
  - "pronouns"
  - "they/them"
  - "she/her"
  - "he/him"
  - "lgbtqia+"
  - "transgender"
  - "female"
  - "male"
  - "nonbinary"
  - "gender"
  - "identity"
  - "advocacy"

race_ethnicity_terms:
  - "Asian"
  - "Black"
  - "African American"
  - "Hispanic"
  - "Latino"
  - "Latinx"
  - "White"
  - "Caucasian"
  - "Native American"
  - "Pacific Islander"
  - "Middle Eastern"
  - "Multiracial"
  - "Biracial"

protected_categories:
  - "disability"
  - "mental health"
  - "physical health"
  - "pregnancy"
  - "veteran"
  - "military status"
  - "religion"
  - "creed"
  - "age"
  - "sexual orientation"
  - "marital status"
  - "familial status"
  - "genetic information"
