# redactor/config/core_patterns.yaml

phone_patterns:
  - name: "us_standard"
    regex: '\(?[0-9]{3}\)?[-. ]?[0-9]{3}[-. ]?[0-9]{4}'
    score: 0.75
    examples: ["(123) 456-7890", "123-456-7890"]
  
  - name: "na_international"
    regex: '\+1-[0-9]{3}-[0-9]{3}-[0-9]{4}'
    score: 0.75
    examples: ["+1-555-123-4567"]
  
  - name: "dot_format"
    regex: '[0-9]{1}[-.][0-9]{3}[-.][0-9]{3}[-.][0-9]{4}'
    score: 0.75
    examples: ["1.555.123.4567"]
  
  - name: "intl_format"
    regex: '\+[0-9]{1,3}[-. ]?[0-9]{1,4}[-. ]?[0-9]{3,4}[-. ]?[0-9]{4}'
    score: 0.75
    examples: ["+44 20 7123 4567"]
  
  - name: "extension_format"
    regex: '(\(?[0-9]{3}\)?[-. ]?[0-9]{3}[-. ]?[0-9]{4})\s*(?:ext|x|ext\.)\s*[0-9]{1,5}'
    score: 0.75
    examples: ["(123) 456-7890 ext 123"]

ssn_patterns:
  - name: "us_ssn"
    regex: '\b(?!000|666|9\d{2})\d{3}-(?!00)\d{2}-(?!0000)\d{4}\b'
    score: 0.75
    examples: ["123-45-6789"]
  
  - name: "us_ssn_spaced"
    regex: '\b(?!000|666|9\d{2})\d{3}\s+(?!00)\d{2}\s+(?!0000)\d{4}\b'
    score: 0.75
    examples: ["123 45 6789"]

context_words:
  phone:
    - "phone"
    - "telephone"
    - "cell"
    - "mobile"
    - "call"
    - "number"
    - "contact"
    - "tel"
    - "office"
    - "support"
    - "fax"
  ssn:
    - "ssn"
    - "social security"
    - "social security number"
    - "tax id"