# redactor/config/core_patterns.yaml

address_patterns:
  - entity_type: "ADDRESS"
    name: "full_address"
    regex: "\\b\\d+\\s+[A-Za-z0-9\\s,]+(?:Street|St|Avenue|Ave|Boulevard|Blvd|Lane|Ln|Road|Rd|Drive|Dr|Court|Ct|Circle|Cir|Way|Parkway|Pkwy)\\s*,?\\s*[A-Za-z\\s]+,\\s*[A-Z]{2}\\s*\\d{5}(?:-\\d{4})?\\b"
    score: 0.9
    examples: ["123 Main St, City, ST 12345", "456 Park Ave, Town, CA 12345-6789"]

  - entity_type: "ADDRESS"
    name: "city_state"
    regex: "\\b[A-Z][a-zA-Z\\s]+,\\s*[A-Z]{2}\\b"
    score: 0.8
    examples: ["San Francisco, CA", "New York, NY"]

  - entity_type: "ADDRESS"
    name: "state_zip"
    regex: "\\b[A-Z]{2}\\s*\\d{5}(?:-\\d{4})?\\b"
    score: 0.9
    examples: ["CA 94105", "NY 10001-1234"]

phone_patterns:
  - name: "us_standard"
    regex: '\(?[0-9]{3}\)?[-. ]?[0-9]{3}[-. ]?[0-9]{4}'
    score: 0.75
    examples: ["(123) 456-7890", "123-456-7890"]
  
  - name: "na_international"
    regex: '\+1-[0-9]{3}-[0-9]{3}-[0-9]{4}'
    score: 0.75
    examples: ["+1-555-123-4567"]
  
  - name: "dot_format"
    regex: '[0-9]{1}[-.][0-9]{3}[-.][0-9]{3}[-.][0-9]{4}'
    score: 0.75
    examples: ["1.555.123.4567"]
  
  - name: "intl_format"
    regex: '\+[0-9]{1,3}[-. ]?[0-9]{1,4}[-. ]?[0-9]{3,4}[-. ]?[0-9]{4}'
    score: 0.75
    examples: ["+44 20 7123 4567"]
  
  - name: "extension_format"
    regex: '(\(?[0-9]{3}\)?[-. ]?[0-9]{3}[-. ]?[0-9]{4})\s*(?:ext|x|ext\.)\s*[0-9]{1,5}'
    score: 0.75
    examples: ["(123) 456-7890 ext 123"]

ssn_patterns:
  - name: "us_ssn"
    regex: '\b(?!000|666|9\d{2})\d{3}-(?!00)\d{2}-(?!0000)\d{4}\b'
    score: 0.75
    examples: ["123-45-6789"]
  
  - name: "us_ssn_spaced"
    regex: '\b(?!000|666|9\d{2})\d{3}\s+(?!00)\d{2}\s+(?!0000)\d{4}\b'
    score: 0.75
    examples: ["123 45 6789"]

context_words:
  phone:
    - "phone"
    - "telephone"
    - "cell"
    - "mobile"
    - "call"
    - "number"
    - "contact"
    - "tel"
    - "office"
    - "support"
    - "fax"
  ssn:
    - "ssn"
    - "social security"
    - "social security number"
    - "tax id"