trigger_words: #"List of patterns that trigger full-line redaction for high-risk entities."
  - "www"
  - "http"
  - "@"
  - ".com"
  - ".co"
  - ".ai"

custom_word_filters:
  keep_words:
    - "Python"
    - "Tableau"
    - "Google Cloud"
    - "AWS"
    - "Power BI"
    - "R"
    - "MATLAB"
    - "Pandas"
    - "scikit-learn"
    - "D3.js"
    - "data"
    - "analytics"
    - "research"
    - "advocacy"
    - "management"
    - "clinical"
    - "healthcare"
    - "biotech"
    - "pharmaceutical"
    - "FDA"
    - "WHO"
    - "NIH"
    - "grant"
