# entity_routing.yaml
settings:
  case_sensitive: false
  enable_partial_matches: true
  debug_mode: true  
  fallback_detector: "presidio"

routing:
  presidio_primary:
    entities:
      - EMAIL_ADDRESS
      - PHONE_NUMBER
      - CREDIT_CARD
      - URL
      - US_SSN
    thresholds:
      EMAIL_ADDRESS: 0.7  # Emails need high confidence
      PHONE_NUMBER: 0.4   # Phone formats vary a lot
      CREDIT_CARD: 0.7   # Financial info needs high confidence
      URL: 0.5           # URLs can vary in format
      US_SSN: 0.6        # SSNs need moderate confidence
    validation:
      require_format: true
      context_check: false

  spacy_primary:
    entities:
      - PERSON
      - LOCATION
      - GPE
      - ORG
      - LOC
      - FAC
      - CARDINAL
    mappings:
      GPE: LOCATION
      LOC: LOCATION
      FAC: LOCATION
      CARDINAL: LOCATION
      ORG: ORGANIZATION
    thresholds:
      PERSON: 0.7
      LOCATION: 0.6
      ORGANIZATION: 0.6
    validation:
      require_format: false
      context_check: true
      context_window: 50

  ensemble_required:
    entities:
      - CERTIFICATION
      - PROFESSIONAL_REFERENCE
      - PORTFOLIO_URL
      - ORGANIZATION
      - TITLE
    confidence_thresholds:
      # Minimum thresholds per entity type
      CERTIFICATION: 
        minimum_combined: 0.80
        minimum_individual: 0.40
        presidio_weight: 0.3
        spacy_weight: 0.7
      PROFESSIONAL_REFERENCE:
        minimum_combined: 0.75
        minimum_individual: 0.35
        presidio_weight: 0.4
        spacy_weight: 0.6
      PORTFOLIO_URL:
        minimum_combined: 0.85
        minimum_individual: 0.45
        presidio_weight: 0.6
        spacy_weight: 0.4
      ORGANIZATION:
        minimum_combined: 0.70
        minimum_individual: 0.35
        presidio_weight: 0.4
        spacy_weight: 0.6
      TITLE:
        minimum_combined: 0.75
        minimum_individual: 0.40
        presidio_weight: 0.3
        spacy_weight: 0.7
    validation:
      context_check: true
      context_window: 75