# redactor/config/entity_routing.yaml
# Purpose: Define routing rules for entity detection between Presidio and spaCy

routing:
  # Entities where Presidio is the primary detector
  presidio_primary:
    entities:
      - EMAIL_ADDRESS
      - PHONE_NUMBER
      - US_SSN
      - CREDIT_CARD
      - US_DRIVER_LICENSE
      - URL
      - IP_ADDRESS
      - DATE_TIME
      - US_PASSPORT
      - US_ITIN
      - UK_NHS
      - IBAN
      - SWIFT_CODE
    confidence_threshold: 0.85
    validation:
      require_format: true  # Strict format validation
      context_check: false  # No context needed for these

  # Entities where spaCy is the primary detector
  spacy_primary:
    entities:
      - PERSON
      - GPE  # Geo-Political Entity
      - NORP  # Nationalities, religious or political groups
      - LANGUAGE
      - LAW
    confidence_threshold: 0.75
    validation:
      require_format: false
      context_check: true
      context_window: 50  # words

  # Entities requiring ensemble approach
  ensemble_required:
    entities:
      - ORGANIZATION  # Companies, institutions
      - TITLE  # Professional titles
      - EDUCATION  # Educational details
      - PROFESSIONAL_REF  # Professional references
      - ACHIEVEMENT  # Professional achievements
    confidence_thresholds:
      minimum_combined: 0.80  # Required combined confidence
      minimum_individual: 0.60  # Minimum per detector
      presidio_weight: 0.4
      spacy_weight: 0.6
    validation:
      context_check: true
      context_window: 75  # words
      minimum_context_matches: 1

# Technical term handling
technical_terms:
  validation:
    context_window: 50  # words
    minimum_context_matches: 1
  categories:
    programming:
      - Python
      - Java
      - JavaScript
      - C++
      - R
    data_science:
      - Tableau
      - Power BI
      - pandas
      - scikit-learn
      - tidyverse
    cloud:
      - AWS
      - Azure
      - GCP
    databases:
      - SQL
      - MongoDB
      - PostgreSQL
    frameworks:
      - Django
      - Flask
      - React
      - Angular

# Context rules for validation
context_rules:
  educational:
    indicators:
      - "University"
      - "Institute"
      - "College"
      - "School"
      - "Academy"
    context_patterns:
      - "study"
      - "studied"
      - "graduate"
      - "degree"
      - "education"
      - "student"
      - "academic"
      - "alumni"

  professional:
    indicators:
      - "Company"
      - "Corporation"
      - "Inc"
      - "Ltd"
      - "LLC"
    context_patterns:
      - "work"
      - "worked"
      - "employed"
      - "position"
      - "role"
      - "job"
      - "career"

# General settings
settings:
  case_sensitive: false
  enable_partial_matches: true
  debug_mode: false  # Enable for detailed detection logging
  fallback_detector: "presidio"  # Default detector if type unknown