settings:
  case_sensitive: false
  enable_partial_matches: true
  debug_mode: true
  enable_context_check: true
  fallback_detector: "presidio"

routing:
  presidio_primary:
    entities:
      - ADDRESS
      - EMAIL_ADDRESS
      - PHONE_NUMBER
      - DATE_TIME
      - URL
      - SOCIAL_MEDIA
      - LOCATION
      - GPA
      - EDUCATIONAL_INSTITUTION
      - DEMOGRAPHIC
    thresholds:
      ADDRESS: 0.8
      EMAIL_ADDRESS: 0.7
      PHONE_NUMBER: 0.8
      DATE_TIME: 0.8  
      URL: 0.5
      SOCIAL_MEDIA: 0.7
      LOCATION: 0.8
      GPA: 0.9
      EDUCATIONAL_INSTITUTION: 0.8
      DEMOGRAPHIC: 0.7
    validation:
      date_ignore_words:
        - "hours"
        - "years"
        - "weekly"
        - "monthly"
        - "minutes"
        - "seconds"
        - "annual"
        - "Published in"
        - "Publication date"
      require_format: true
      context_check: true
      context_words:
        - university
        - college
        - institute
        - school
        - diversity
        - inclusion
        - initiative

  spacy_primary:
    entities:
      - PERSON
      - GPE
    mappings:
      GPE: LOCATION_FULL
    thresholds:
      PERSON: 0.9

  ensemble_required:
    entities:
      - LOCATION_FULL
      - EDUCATIONAL_INSTITUTION
      - DEMOGRAPHIC
    confidence_thresholds:
      DEMOGRAPHIC:
        minimum_combined: 0.7
        presidio_weight: 0.5
        spacy_weight: 0.5
      EDUCATIONAL_INSTITUTION:
        minimum_combined: 0.75
        presidio_weight: 0.5
        spacy_weight: 0.5
      LOCATION_FULL:
        minimum_combined: 0.7
        presidio_weight: 0.6
        spacy_weight: 0.4