settings:
  case_sensitive: false
  enable_partial_matches: true
  debug_mode: true
  enable_context_check: true
  fallback_detector: "presidio"

routing:
  presidio_primary:
    entities:
      - ADDRESS
      - EMAIL_ADDRESS
      - PHONE_NUMBER
      - INTERNET_REFERENCE 
      - LOCATION
      - GPA
      - EDUCATIONAL_INSTITUTION
      - OTHER_ID
    thresholds:
      ADDRESS: 0.8
      EMAIL_ADDRESS: 0.7
      PHONE_NUMBER: 0.8
      DATE_TIME: 0.8  
      INTERNET_REFERENCE: 0.7
      LOCATION: 0.8
      GPA: 0.9
      EDUCATIONAL_INSTITUTION: 0.8
    validation:
      date_ignore_words:
        - "hours"
        - "years"
        - "weekly"
        - "monthly"
        - "minutes"
        - "seconds"
        - "annual"
        - "Published in"
        - "Publication date"
      require_format: true
      context_check: true
      context_words:
        - university
        - college
        - institute
        - school
        - diversity
        - inclusion
        - initiative

  spacy_primary:
    entities:
      - PERSON
    thresholds:
      PERSON: 0.6

  ensemble_required:
    entities:
      - DATE_TIME
      - EDUCATIONAL_INSTITUTION
      - PHI
      - PROTECTED_CLASS
    confidence_thresholds:
      DATE_TIME:     
        minimum_combined: 0.7
        presidio_weight: 0.65
        spacy_weight: 0.35
      EDUCATIONAL_INSTITUTION:
        minimum_combined: 0.75
        presidio_weight: 0.5
        spacy_weight: 0.5
      PROTECTED_CLASS:
        minimum_combined: 0.6
        presidio_weight: 0.35
        spacy_weight: 0.65
      PHI:
        minimum_combined: 0.6
        presidio_weight: 0.5
        spacy_weight: 0.5